substitutions:
  device_name: guest-bathroom-leds
  friendly_name: Guest Bathroom LEDs

packages:
  common: !include .common.yaml

esp32:
  board: wemos_d1_mini32

  framework:
    type: esp-idf
    version: recommended

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

output:
  - platform: ledc
    pin: GPIO04
    id: gpio_04

light:
  - platform: monochromatic
    output: gpio_04
    name: "LED Strips"
    default_transition_length: 500ms
    restore_mode: RESTORE_DEFAULT_ON
