substitutions:
  device_name: outdoor-plug-1
  friendly_name: Outdoor Plug 1

  # Higher value gives lower watt readout
  current_res: "0.001"
  # Lower value gives lower voltage readout
  voltage_div: "770"

<<: !include ./wyze/outdoor-plug.yaml

esphome:
  name: ${device_name}
  platform: ESP32
  board: esp-wrover-kit
