power:
  name: "${friendly_name} BMS ${bms_number} power"
  internal: true
charging_power:
  name: "${friendly_name} BMS ${bms_number} charging power"
  internal: true
discharging_power:
  name: "${friendly_name} BMS ${bms_number} discharging power"
  internal: true

nominal_capacity:
  name: "${friendly_name} BMS ${bms_number} nominal capacity"
  internal: true
charging_cycles:
  name: "${friendly_name} BMS ${bms_number} charging cycles"
  disabled_by_default: true

battery_cycle_capacity:
  name: "${friendly_name} BMS ${bms_number} battery cycle capacity"
  internal: true

average_cell_voltage:
  id: bms_${bms_number}_average_cell_voltage

min_cell_voltage:
  id: bms_${bms_number}_min_cell_voltage
max_cell_voltage:
  id: bms_${bms_number}_max_cell_voltage
min_voltage_cell:
  id: bms_${bms_number}_min_voltage_cell
max_voltage_cell:
  id: bms_${bms_number}_max_voltage_cell
temperature_1:
  id: bms_${bms_number}_temperature_1
temperature_2:
  id: bms_${bms_number}_temperature_2
temperature_3:
  id: bms_${bms_number}_temperature_3
