# ble_client:
#   - id: client${bms_number}
#     mac_address: ${mac_address}
#     auto_connect: False

# jbd_bms_ble:
#   - id: bms${bms_number}
#     ble_client_id: client${bms_number}
#     update_interval: 10s

# binary_sensor:
#   - platform: jbd_bms_ble
#     jbd_bms_ble_id: bms${bms_number}
#     online_status:
#       id: bms_${bms_number}_online_status
#       on_state:
#         if:
#           condition:
#             lambda: "return (x);"
#           then:
#             - lvgl.page.show:
#                 id: main_page
#             - globals.set:
#                 id: demo_mode
#                 value: "false"
#     balancing:
#       id: bms_${bms_number}_balancing
#     charging:
#       id: bms_${bms_number}_charging
#     discharging:
#       id: bms_${bms_number}_discharging

sensor:
  # - platform: jbd_bms_ble
  #   jbd_bms_ble_id: bms${bms_number}
  #   <<: !include
  #     file: .bms_sensors.yaml
  #     # vars:
  #     # bms_number: ${bms_number}
  - platform: template
    id: bms_${bms_number}_max_cell_delta
    on_value:
      then:
        - lvgl.label.update:
            id: bms_${bms_number}_max_cell_delta_label
            text:
              format: "%.3fv"
              args:
                - "x"
  - platform: packet_transport
    provider: golf-cart-bms
    id: bms_${bms_number}_state_of_charge
    remote_id: bms_${bms_number}_soc
    # name: "${friendly_name} BMS 1 state of charge"
    filters:
      - delta: 1
    on_value:
      then:
        - lvgl.label.update:
            id: bms_1_soc_label
            text:
              format: "%.2f%%"
              args:
                - "x"
  - platform: packet_transport
    provider: golf-cart-bms
    id: bms_${bms_number}_max_discharge_current
    on_value:
      then:
        - lvgl.label.update:
            id: bms_${bms_number}_max_discharge_current_label
            text:
              format: "%.3fA"
              args:
                - "x"
  - platform: packet_transport
    provider: golf-cart-bms
    id: bms_${bms_number}_capacity_remaining
    filters:
      - delta: 0.005
    on_value:
      then:
        - lvgl.label.update:
            id: bms_${bms_number}_remaining_capacity_label
            text:
              format: "%.2fAh"
              args:
                - "x"
  - platform: packet_transport
    provider: golf-cart-bms
    id: bms_${bms_number}_delta_cell_voltage
    on_value:
      then:
        - lvgl.label.update:
            id: bms_${bms_number}_cell_delta_label
            text:
              format: "%.3fv"
              args:
                - "x"
        - sensor.template.publish:
            id: bms_${bms_number}_max_cell_delta
            state: !lambda |-
              static float max_delta = 0.0;
              if (x > max_delta) {
                max_delta = x;
              }
              return max_delta;
  # - platform: packet_transport
  #   provider: golf-cart-bms

  - platform: template
    id: bms_${bms_number}_max_charge_current
    on_value:
      then:
        - lvgl.label.update:
            id: bms_${bms_number}_max_charge_current_label
            text:
              format: "%.3fA"
              args:
                - "x"
  - platform: packet_transport
    provider: golf-cart-bms
    id: bms_${bms_number}_current
    filters:
      - delta: 0.05
    on_value:
      then:
        - lvgl.label.update:
            id: bms_${bms_number}_current_label
            text:
              format: "%.2fA"
              args:
                - "x"
        - if:
            condition:
              lambda: |-
                return x > 0;
            then:
              - sensor.template.publish:
                  id: bms_${bms_number}_max_charge_current
                  state: !lambda |-
                    static float max_charge = 0.0;
                    if (x > max_charge) {
                      max_charge = x;
                    }
                    return max_charge;
            else:
              - sensor.template.publish:
                  id: bms_${bms_number}_max_discharge_current
                  state: !lambda |-
                    static float max_discharge = 0.0;
                    if (x < max_discharge) {
                      max_discharge = x;
                    }
                    return max_discharge;

  - platform: packet_transport
    provider: golf-cart-bms
    id: bms_${bms_number}_max_voltage
    on_value:
      then:
        - lvgl.label.update:
            id: bms_${bms_number}_max_voltage_label
            text:
              format: "%.3fv"
              args:
                - "x"
  - platform: packet_transport
    provider: golf-cart-bms
    id: bms_${bms_number}_min_voltage
    on_value:
      then:
        - lvgl.label.update:
            id: bms_${bms_number}_min_voltage_label
            text:
              format: "%.3fv"
              args:
                - "x"
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 1
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 2
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 3
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 4
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 5
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 6
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 7
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 8
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 9
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 10
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 11
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 12
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 13
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 14
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 15
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 16
