sensor:
  - platform: template
    id: bms_${bms_number}_max_cell_delta
    on_value:
      then:
        - lvgl.label.update:
            id: bms_${bms_number}_max_cell_delta_label
            text:
              format: "%.3fv"
              args:
                - "x"
  - platform: packet_transport
    provider: golf-cart-bms
    id: bms_${bms_number}_state_of_charge
    remote_id: bms_${bms_number}_soc
    filters:
      - delta: 1
    on_value:
      then:
        - lvgl.label.update:
            id: bms_1_soc_label
            text:
              format: "%.2f%%"
              args:
                - "x"
  - platform: packet_transport
    provider: golf-cart-bms
    id: bms_${bms_number}_max_discharge_current
    remote_id: bms_${bms_number}_max_dc
    on_value:
      then:
        - lvgl.label.update:
            id: bms_${bms_number}_max_discharge_current_label
            text:
              format: "%.3fA"
              args:
                - "x"
  - platform: packet_transport
    provider: golf-cart-bms
    id: bms_${bms_number}_capacity_remaining
    remote_id: bms_${bms_number}_caprem
    filters:
      - delta: 0.005
    on_value:
      then:
        - lvgl.label.update:
            id: bms_${bms_number}_remaining_capacity_label
            text:
              format: "%.2fAh"
              args:
                - "x"
  - platform: packet_transport
    provider: golf-cart-bms
    id: bms_${bms_number}_delta_cell_voltage
    remote_id: bms_${bms_number}_dcv
    on_value:
      then:
        - lvgl.label.update:
            id: bms_${bms_number}_cell_delta_label
            text:
              format: "%.3fv"
              args:
                - "x"
        - sensor.template.publish:
            id: bms_${bms_number}_max_cell_delta
            state: !lambda |-
              static float max_delta = 0.0;
              if (x > max_delta) {
                max_delta = x;
              }
              return max_delta;

  - platform: packet_transport
    provider: golf-cart-bms
    id: bms_${bms_number}_max_charge_current
    remote_id: bms_${bms_number}_max_cc
    on_value:
      then:
        - lvgl.label.update:
            id: bms_${bms_number}_max_charge_current_label
            text:
              format: "%.3fA"
              args:
                - "x"
  - platform: packet_transport
    provider: golf-cart-bms
    id: bms_${bms_number}_current
    filters:
      - delta: 0.05
    on_value:
      then:
        - lvgl.label.update:
            id: bms_${bms_number}_current_label
            text:
              format: "%.2fA"
              args:
                - "x"
  - platform: packet_transport
    provider: golf-cart-bms
    id: bms_${bms_number}_voltage
    on_value:
      then:
        - lvgl.label.update:
            id: bms_${bms_number}_voltage_label
            text:
              format: "%.3fv"
              args:
                - "x"
  - platform: packet_transport
    provider: golf-cart-bms
    id: bms_${bms_number}_max_voltage
    on_value:
      then:
        - lvgl.label.update:
            id: bms_${bms_number}_max_voltage_label
            text:
              format: "%.3fv"
              args:
                - "x"
  - platform: packet_transport
    provider: golf-cart-bms
    id: bms_${bms_number}_min_voltage
    on_value:
      then:
        - lvgl.label.update:
            id: bms_${bms_number}_min_voltage_label
            text:
              format: "%.3fv"
              args:
                - "x"
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 1
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 2
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 3
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 4
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 5
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 6
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 7
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 8
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 9
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 10
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 11
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 12
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 13
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 14
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 15
  - !include
    file: .cell_voltage_sensor.yaml
    vars:
      cell_number: 16
