- name: BMS ${bms_number} Cells
  id: bms_${bms_number}_cells_tab
  widgets:
    - obj: # a properly placed coontainer object for all these controls
        align: TOP_RIGHT
        width: 100%
        height: 100%
        pad_all: 2
        bg_opa: TRANSP
        border_opa: TRANSP
        layout:
          pad_row: 2
          pad_column: 8
          type: GRID # split the rows and the columns proportionally
          grid_columns: [FR(1), FR(10), FR(1), FR(10)]
          grid_rows: [FR(1), FR(1), FR(1), FR(1), FR(1), FR(1), FR(1), FR(1)]
        widgets:
          - label:
              text: "1"
              text_align: RIGHT
              grid_cell_column_pos: 0
              grid_cell_row_pos: 0
              grid_cell_x_align: STRETCH
              grid_cell_y_align: CENTER
          - bar:
              id: bms_${bms_number}_cell_1_bar
              grid_cell_column_pos: 1
              grid_cell_row_pos: 0
              grid_cell_x_align: STRETCH
              grid_cell_y_align: STRETCH
              min_value: 0
              max_value: 365
          - label:
              id: bms_${bms_number}_cell_1_label
              text: "-.--v"
              styles: cell_voltage_label_style
              grid_cell_column_pos: 1
              grid_cell_row_pos: 0
          - label:
              text: "2"
              text_align: RIGHT
              grid_cell_column_pos: 0
              grid_cell_row_pos: 1
              grid_cell_x_align: STRETCH
              grid_cell_y_align: CENTER
          - bar:
              id: bms_${bms_number}_cell_2_bar
              grid_cell_column_pos: 1
              grid_cell_row_pos: 1
              grid_cell_x_align: STRETCH
              grid_cell_y_align: STRETCH
              min_value: 0
              max_value: 365
          - label:
              id: bms_${bms_number}_cell_2_label
              text: "-.--v"
              styles: cell_voltage_label_style
              grid_cell_column_pos: 1
              grid_cell_row_pos: 1
          - label:
              text: "3"
              text_align: RIGHT
              grid_cell_column_pos: 0
              grid_cell_row_pos: 2
              grid_cell_x_align: STRETCH
              grid_cell_y_align: CENTER
          - bar:
              id: bms_${bms_number}_cell_3_bar
              grid_cell_column_pos: 1
              grid_cell_row_pos: 2
              grid_cell_x_align: STRETCH
              grid_cell_y_align: STRETCH
              min_value: 0
              max_value: 365
          - label:
              id: bms_${bms_number}_cell_3_label
              text: "-.--v"
              styles: cell_voltage_label_style
              grid_cell_column_pos: 1
              grid_cell_row_pos: 2
          - label:
              text: "4"
              text_align: RIGHT
              grid_cell_column_pos: 0
              grid_cell_row_pos: 3
              grid_cell_x_align: STRETCH
              grid_cell_y_align: CENTER
          - bar:
              id: bms_${bms_number}_cell_4_bar
              grid_cell_column_pos: 1
              grid_cell_row_pos: 3
              grid_cell_x_align: STRETCH
              grid_cell_y_align: STRETCH
              min_value: 0
              max_value: 365
          - label:
              id: bms_${bms_number}_cell_4_label
              text: "-.--v"
              styles: cell_voltage_label_style
              grid_cell_column_pos: 1
              grid_cell_row_pos: 3
          - label:
              text: "5"
              text_align: RIGHT
              grid_cell_column_pos: 0
              grid_cell_row_pos: 4
              grid_cell_x_align: STRETCH
              grid_cell_y_align: CENTER
          - bar:
              id: bms_${bms_number}_cell_5_bar
              grid_cell_column_pos: 1
              grid_cell_row_pos: 4
              grid_cell_x_align: STRETCH
              grid_cell_y_align: STRETCH
              min_value: 0
              max_value: 365
          - label:
              id: bms_${bms_number}_cell_5_label
              text: "-.--v"
              styles: cell_voltage_label_style
              grid_cell_column_pos: 1
              grid_cell_row_pos: 4
          - label:
              text: "6"
              text_align: RIGHT
              grid_cell_column_pos: 0
              grid_cell_row_pos: 5
              grid_cell_x_align: STRETCH
              grid_cell_y_align: CENTER
          - bar:
              id: bms_${bms_number}_cell_6_bar
              grid_cell_column_pos: 1
              grid_cell_row_pos: 5
              grid_cell_x_align: STRETCH
              grid_cell_y_align: STRETCH
              min_value: 0
              max_value: 365
          - label:
              id: bms_${bms_number}_cell_6_label
              text: "-.--v"
              styles: cell_voltage_label_style
              grid_cell_column_pos: 1
              grid_cell_row_pos: 5
          - label:
              text: "7"
              text_align: RIGHT
              grid_cell_column_pos: 0
              grid_cell_row_pos: 6
              grid_cell_x_align: STRETCH
              grid_cell_y_align: CENTER
          - bar:
              id: bms_${bms_number}_cell_7_bar
              grid_cell_column_pos: 1
              grid_cell_row_pos: 6
              grid_cell_x_align: STRETCH
              grid_cell_y_align: STRETCH
              min_value: 0
              max_value: 365
          - label:
              id: bms_${bms_number}_cell_7_label
              text: "-.--v"
              styles: cell_voltage_label_style
              grid_cell_column_pos: 1
              grid_cell_row_pos: 6
          - label:
              text: "8"
              text_align: RIGHT
              grid_cell_column_pos: 0
              grid_cell_row_pos: 7
              grid_cell_x_align: STRETCH
              grid_cell_y_align: CENTER
          - bar:
              id: bms_${bms_number}_cell_8_bar
              grid_cell_column_pos: 1
              grid_cell_row_pos: 7
              grid_cell_x_align: STRETCH
              grid_cell_y_align: STRETCH
              min_value: 0
              max_value: 365
          - label:
              id: bms_${bms_number}_cell_8_label
              text: "-.--v"
              styles: cell_voltage_label_style
              grid_cell_column_pos: 1
              grid_cell_row_pos: 7
          - label:
              text: "9"
              text_align: RIGHT
              grid_cell_column_pos: 2
              grid_cell_row_pos: 0
              grid_cell_x_align: STRETCH
              grid_cell_y_align: CENTER
          - bar:
              id: bms_${bms_number}_cell_9_bar
              grid_cell_column_pos: 3
              grid_cell_row_pos: 0
              grid_cell_x_align: STRETCH
              grid_cell_y_align: STRETCH
              min_value: 0
              max_value: 365
          - label:
              id: bms_${bms_number}_cell_9_label
              text: "-.--v"
              styles: cell_voltage_label_style
              grid_cell_column_pos: 3
              grid_cell_row_pos: 0
          - label:
              text: "10"
              text_align: RIGHT
              grid_cell_column_pos: 2
              grid_cell_row_pos: 1
              grid_cell_x_align: STRETCH
              grid_cell_y_align: CENTER
          - bar:
              id: bms_${bms_number}_cell_10_bar
              grid_cell_column_pos: 3
              grid_cell_row_pos: 1
              grid_cell_x_align: STRETCH
              grid_cell_y_align: STRETCH
              min_value: 0
              max_value: 365
          - label:
              id: bms_${bms_number}_cell_10_label
              text: "-.--v"
              styles: cell_voltage_label_style
              grid_cell_column_pos: 3
              grid_cell_row_pos: 1
          - label:
              text: "11"
              text_align: RIGHT
              grid_cell_column_pos: 2
              grid_cell_row_pos: 2
              grid_cell_x_align: STRETCH
              grid_cell_y_align: CENTER
          - bar:
              id: bms_${bms_number}_cell_11_bar
              grid_cell_column_pos: 3
              grid_cell_row_pos: 2
              grid_cell_x_align: STRETCH
              grid_cell_y_align: STRETCH
              min_value: 0
              max_value: 365
          - label:
              id: bms_${bms_number}_cell_11_label
              text: "-.--v"
              styles: cell_voltage_label_style
              grid_cell_column_pos: 3
              grid_cell_row_pos: 2
          - label:
              text: "12"
              text_align: RIGHT
              grid_cell_column_pos: 2
              grid_cell_row_pos: 3
              grid_cell_x_align: STRETCH
              grid_cell_y_align: CENTER
          - bar:
              id: bms_${bms_number}_cell_12_bar
              grid_cell_column_pos: 3
              grid_cell_row_pos: 3
              grid_cell_x_align: STRETCH
              grid_cell_y_align: STRETCH
              min_value: 0
              max_value: 365
          - label:
              id: bms_${bms_number}_cell_12_label
              text: "-.--v"
              styles: cell_voltage_label_style
              grid_cell_column_pos: 3
              grid_cell_row_pos: 3
          - label:
              text: "13"
              text_align: RIGHT
              grid_cell_column_pos: 2
              grid_cell_row_pos: 4
              grid_cell_x_align: STRETCH
              grid_cell_y_align: CENTER
          - bar:
              id: bms_${bms_number}_cell_13_bar
              grid_cell_column_pos: 3
              grid_cell_row_pos: 4
              grid_cell_x_align: STRETCH
              grid_cell_y_align: STRETCH
              min_value: 0
              max_value: 365
          - label:
              id: bms_${bms_number}_cell_13_label
              text: "-.--v"
              styles: cell_voltage_label_style
              grid_cell_column_pos: 3
              grid_cell_row_pos: 4
          - label:
              text: "14"
              text_align: RIGHT
              grid_cell_column_pos: 2
              grid_cell_row_pos: 5
              grid_cell_x_align: STRETCH
              grid_cell_y_align: CENTER
          - bar:
              id: bms_${bms_number}_cell_14_bar
              grid_cell_column_pos: 3
              grid_cell_row_pos: 5
              grid_cell_x_align: STRETCH
              grid_cell_y_align: STRETCH
              min_value: 0
              max_value: 365
          - label:
              id: bms_${bms_number}_cell_14_label
              text: "-.--v"
              styles: cell_voltage_label_style
              grid_cell_column_pos: 3
              grid_cell_row_pos: 5
          - label:
              text: "15"
              text_align: RIGHT
              grid_cell_column_pos: 2
              grid_cell_row_pos: 6
              grid_cell_x_align: STRETCH
              grid_cell_y_align: CENTER
          - bar:
              id: bms_${bms_number}_cell_15_bar
              grid_cell_column_pos: 3
              grid_cell_row_pos: 6
              grid_cell_x_align: STRETCH
              grid_cell_y_align: STRETCH
              min_value: 0
              max_value: 365
          - label:
              id: bms_${bms_number}_cell_15_label
              text: "-.--v"
              styles: cell_voltage_label_style
              grid_cell_column_pos: 3
              grid_cell_row_pos: 6
          - label:
              text: "16"
              text_align: RIGHT
              grid_cell_column_pos: 2
              grid_cell_row_pos: 7
              grid_cell_x_align: STRETCH
              grid_cell_y_align: CENTER
          - bar:
              id: bms_${bms_number}_cell_16_bar
              grid_cell_column_pos: 3
              grid_cell_row_pos: 7
              grid_cell_x_align: STRETCH
              grid_cell_y_align: STRETCH
              min_value: 0
              max_value: 365
          - label:
              id: bms_${bms_number}_cell_16_label
              text: "-.--v"
              styles: cell_voltage_label_style
              grid_cell_column_pos: 3
              grid_cell_row_pos: 7
