- obj:
    align: CENTER
    width: 100%
    height: 100%
    pad_all: 0
    bg_opa: TRANSP
    border_opa: TRANSP
    scrollable: false
    layout:
      type: FLEX
      flex_flow: COLUMN
      flex_align_main: CENTER
      flex_align_cross: CENTER
      pad_row: 10
    widgets:
      # Status info
      - obj:
          width: 100%
          height: 60
          bg_opa: TRANSP
          border_opa: TRANSP
          pad_left: 40
          pad_right: 40
          layout:
            type: FLEX
            flex_flow: ROW
            flex_align_main: SPACE_BETWEEN
            flex_align_cross: CENTER
          widgets:
            - label:
                id: gear_label
                text: "N"
                text_font: montserrat_20
                text_color: 0x00FF88
            - label:
                text: "READY"
                text_font: montserrat_20
                text_color: 0x00FF88
            - label:
                text: "50.1V"
                text_font: montserrat_14
                text_color: 0xFFFFFF
      # Large digital speed display
      - obj:
          width: 500
          height: 300
          bg_color: 0x1A1A2E
          bg_grad_color: 0x16213E
          bg_grad_dir: VER
          border_width: 3
          border_color: 0x4DA6FF
          radius: 15
          align: CENTER
          widgets:
            - label:
                id: speed_label
                align: CENTER
                y: -60
                text: "0.0"
                text_font: montserrat_140
                text_color: 0x4DA6FF
                text_align: CENTER
            - label:
                align: CENTER
                y: -10
                text: "mph"
                text_font: montserrat_14
                text_color: 0x888888
            - label:
                align: CENTER
                y: 20
                text: "SPEED"
                text_font: montserrat_14
                text_color: 0x666666
      
      # Current display
      - obj:
          width: 300
          height: 80
          bg_color: 0x2A1A1A
          border_width: 2
          border_color: 0xFF6B35
          radius: 10
          align: CENTER
          widgets:
            - label:
                id: current_label
                align: CENTER
                y: -10
                text: "0.0A"
                text_font: montserrat_20
                text_color: 0xFF6B35
            - label:
                align: CENTER
                y: 15
                text: "CURRENT"
                text_font: montserrat_10
                text_color: 0x888888