state_of_charge:
  id: bms_${bms_number}_state_of_charge
  name: ${bms_number} State of charge
  filters:
    - delta: 0.5

capacity_remaining:
  name: ${bms_number} Capacity remaining
  id: bms_${bms_number}_capacity_remaining
  filters:
    - delta: 0.005

current:
  id: bms_${bms_number}_current
  filters:
    - delta: 0.05
  on_value:
      - if:
          condition:
            lambda: |-
              return x > 0;
          then:
            - sensor.template.publish:
                id: bms_${bms_number}_max_charge_current
                state: !lambda |-
                  static float max_charge = 0.0;
                  if (x > max_charge) {
                    max_charge = x;
                    return max_charge;
                  }
                  return {};
          else:
            - sensor.template.publish:
                id: bms_${bms_number}_max_discharge_current
                state: !lambda |-
                  static float max_discharge = 0.0;
                  if (x < max_discharge) {
                    max_discharge = x;
                    return max_discharge;
                  }
                  return {};

power:
  name: ${bms_number} Power
  disabled_by_default: true

charging_power:
  name: ${bms_number} Charging power
  disabled_by_default: true

discharging_power:
  name: ${bms_number} Discharging power
  disabled_by_default: true

nominal_capacity:
  name: ${bms_number} Nominal capacity
  disabled_by_default: true

charging_cycles:
  name: ${bms_number} Charging cycles
  disabled_by_default: true

battery_cycle_capacity:
  name: ${bms_number} Cycle capacity
  disabled_by_default: true

total_voltage:
  name: ${bms_number} Total voltage
  disabled_by_default: true

  filters:
    - delta: 0.01
  on_value:
      - sensor.template.publish:
          id: bms_${bms_number}_max_voltage
          state: !lambda |-
            static float max_voltage = 0.0;
            if (x > max_voltage) {
              max_voltage = x;
            }
            return max_voltage;
      - sensor.template.publish:
          id: bms_${bms_number}_min_voltage
          state: !lambda |-
            static float min_voltage = 0.0;
            if (x < min_voltage || min_voltage == 0.0) {
              min_voltage = x;
            }
            return min_voltage;
average_cell_voltage:
  name: ${bms_number} Average cell voltage
  id: bms_${bms_number}_average_cell_voltage
  disabled_by_default: true
delta_cell_voltage:
  name: ${bms_number} Delta cell voltage
  id: bms_${bms_number}_delta_cell_voltage
  disabled_by_default: true
  on_value:
    - sensor.template.publish:
        id: bms_${bms_number}_max_cell_delta_voltage
        state: !lambda |-
          static float max_delta = 0.0;
          if (x > max_delta) {
            max_delta = x;
          }
          return max_delta;

min_cell_voltage:
  name: ${bms_number} Min cell voltage
  id: bms_${bms_number}_min_cell_voltage
  disabled_by_default: true
max_cell_voltage:
  name: ${bms_number} Max cell voltage
  id: bms_${bms_number}_max_cell_voltage
  disabled_by_default: true
min_voltage_cell:
  id: bms_${bms_number}_min_voltage_cell
max_voltage_cell:
  id: bms_${bms_number}_max_voltage_cell
temperature_1:
  id: bms_${bms_number}_temperature_1
  filters:
    - delta: 0.1
temperature_2:
  id: bms_${bms_number}_temperature_2
  filters:
    - delta: 0.1
temperature_3:
  id: bms_${bms_number}_temperature_3
  filters:
    - delta: 0.1
cell_voltage_1: !include
  file: .cell_voltage_sensor.yaml
  vars:
    cell_number: 1
cell_voltage_2: !include
  file: .cell_voltage_sensor.yaml
  vars:
    cell_number: 2
cell_voltage_3: !include
  file: .cell_voltage_sensor.yaml
  vars:
    cell_number: 3
cell_voltage_4: !include
  file: .cell_voltage_sensor.yaml
  vars:
    cell_number: 4
cell_voltage_5: !include
  file: .cell_voltage_sensor.yaml
  vars:
    cell_number: 5
cell_voltage_6: !include
  file: .cell_voltage_sensor.yaml
  vars:
    cell_number: 6
cell_voltage_7: !include
  file: .cell_voltage_sensor.yaml
  vars:
    cell_number: 7
cell_voltage_8: !include
  file: .cell_voltage_sensor.yaml
  vars:
    cell_number: 8
cell_voltage_9: !include
  file: .cell_voltage_sensor.yaml
  vars:
    cell_number: 9
cell_voltage_10: !include
  file: .cell_voltage_sensor.yaml
  vars:
    cell_number: 10
cell_voltage_11: !include
  file: .cell_voltage_sensor.yaml
  vars:
    cell_number: 11
cell_voltage_12: !include
  file: .cell_voltage_sensor.yaml
  vars:
    cell_number: 12
cell_voltage_13: !include
  file: .cell_voltage_sensor.yaml
  vars:
    cell_number: 13
cell_voltage_14: !include
  file: .cell_voltage_sensor.yaml
  vars:
    cell_number: 14
cell_voltage_15: !include
  file: .cell_voltage_sensor.yaml
  vars:
    cell_number: 15
cell_voltage_16: !include
  file: .cell_voltage_sensor.yaml
  vars:
    cell_number: 16
