substitutions:
  device_name: golf-cart-bms
  friendly_name: Golf Cart BMS
  bms_number: "1"

esphome:
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.arduino.memory_type: qio_opi
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 4MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

# web_server:
#   include_internal: true
#   port: 80

# led GPIO21

wifi:
  output_power: 10
  reboot_timeout: 0s # disable reboot on wifi disconnect

api:
  reboot_timeout: 0s # disable reboot on api disconnect

logger:
  # baud_rate: 0
  # hardware_uart: UART0
  level: INFO

external_components:
  - source: github://syssi/esphome-jbd-bms@main

packages:
  common: !include ../.common.yaml
  bms_config_1: !include
    file: bms/.bms_config.yaml
    vars:
      bms_number: 1
      tx_pin: 7
      rx_pin: 8
      update_interval: 750ms
      rx_timeout: 150ms
  bms_config_2: !include
    file: bms/.bms_config.yaml
    vars:
      bms_number: 2
      tx_pin: 9
      rx_pin: 10
      update_interval: 750ms
      rx_timeout: 150ms

uart:
  - id: uart_modbus_server
    baud_rate: 115200
    tx_pin: 11
    rx_pin: 12

# modbus:
#   - uart_id: uart_modbus_server
#     id: modbus_server
#     role: server

udp:
  - addresses:
      - 192.168.2.153

packet_transport:
  platform: udp
  update_interval: 1s
  sensors:
    - bms_${bms_number}_current
    - id: bms_${bms_number}_capacity_remaining
      broadcast_id: bms_${bms_number}_caprem
    - id: bms_${bms_number}_state_of_charge
      broadcast_id: bms_${bms_number}_soc
    - bms_${bms_number}_voltage
    - bms_${bms_number}_max_voltage
    - bms_${bms_number}_min_voltage
    - id: bms_${bms_number}_delta_cell_voltage
      broadcast_id: bms_${bms_number}_dcv
    - id: bms_${bms_number}_average_cell_voltage
      broadcast_id: bms_${bms_number}_acv
    - id: bms_${bms_number}_max_charge_current
      broadcast_id: bms_${bms_number}_max_cc
    - id: bms_${bms_number}_max_discharge_current
      broadcast_id: bms_${bms_number}_max_dc
    - id: bms_${bms_number}_cell_16_voltage_sensor
      broadcast_id: bms_${bms_number}_c16v
    - id: bms_${bms_number}_cell_1_voltage_sensor
      broadcast_id: bms_${bms_number}_c1v
    - id: bms_${bms_number}_cell_2_voltage_sensor
      broadcast_id: bms_${bms_number}_c2v
    - id: bms_${bms_number}_cell_3_voltage_sensor
      broadcast_id: bms_${bms_number}_c3v
    - id: bms_${bms_number}_cell_4_voltage_sensor
      broadcast_id: bms_${bms_number}_c4v
    - id: bms_${bms_number}_cell_5_voltage_sensor
      broadcast_id: bms_${bms_number}_c5v
    - id: bms_${bms_number}_cell_6_voltage_sensor
      broadcast_id: bms_${bms_number}_c6v
    - id: bms_${bms_number}_cell_7_voltage_sensor
      broadcast_id: bms_${bms_number}_c7v
    - id: bms_${bms_number}_cell_8_voltage_sensor
      broadcast_id: bms_${bms_number}_c8v
    - id: bms_${bms_number}_cell_9_voltage_sensor
      broadcast_id: bms_${bms_number}_c9v
    - id: bms_${bms_number}_cell_10_voltage_sensor
      broadcast_id: bms_${bms_number}_c10v
    - id: bms_${bms_number}_cell_11_voltage_sensor
      broadcast_id: bms_${bms_number}_c11v
    - id: bms_${bms_number}_cell_12_voltage_sensor
      broadcast_id: bms_${bms_number}_c12v
    - id: bms_${bms_number}_cell_13_voltage_sensor
      broadcast_id: bms_${bms_number}_c13v
    - id: bms_${bms_number}_cell_14_voltage_sensor
      broadcast_id: bms_${bms_number}_c14v
    - id: bms_${bms_number}_cell_15_voltage_sensor
      broadcast_id: bms_${bms_number}_c15v
# sensor:
#   - platform: combination
#     type: sum
#     name: "Total Current"
#     internal: true
#     sources:
#       - source: bms_1_current
#       - source: bms_2_current

#   - platform: combination
#     type: max
#     id: max_combined_discharge_current
#     sources:
#       - source: bms_1_max_discharge_current
#       - source: bms_2_max_discharge_current
