substitutions:
  device_name: golf-cart
  friendly_name: Golf Cart
  rx_timeout: 150ms

  TP_IRQ: GPIO04
  # TP_SDA: GPIO08
  # TP_SCL: GPIO09
  SPI_MOSI: GPIO11
  # SPI_CLK:
  I2C_SDA: GPIO08
  I2C_SCL: GPIO09

# GPIO8(SDA) and GPIO9(SCL)

external_components:
  - source: ../components
    components: [navitas_tac]

packages:
  common: !include ../.common.yaml
  base: !include display/.base.yaml
  bms_1: !include
    file: display/.bms_config.yaml
    vars:
      bms_number: 1
      mac_address: A4:C1:37:34:2B:B3
  bms_2: !include
    file: display/.bms_config.yaml
    vars:
      bms_number: 2
      mac_address: A4:C1:37:00:4E:EA

logger:
  level: INFO
  initial_level: INFO
  logs:
    packet_transport: INFO

ota:
  on_begin:
    then:
      - esp32_ble_tracker.stop_scan:
      - lvgl.pause:
      - ble_client.disconnect: navitas_tac_ble_client

esp32_ble_tracker:
  # scan_parameters:
  #   active: false

ble_client:
  - mac_address: DA:50:28:DB:EC:DF
    id: navitas_tac_ble_client

# Navitas TAC Controller component
navitas_tac:
  ble_client_id: navitas_tac_ble_client
  id: tac_controller
  update_interval: 250ms

udp:

packet_transport:
  platform: udp

uart:
  - id: uart_modbus_client
    baud_rate: 115200
    tx_pin: 16
    rx_pin: 15

font:
  - file: "gfonts://Montserrat"
    id: montserrat_140
    size: 140
    glyphs: '!"%()+,-.0123456789:?ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz°'

lvgl:
  log_level: WARN
  touchscreens:
    - touchscreen_id: touch_screen

  color_depth: 16
  text_font: montserrat_20
  align: center
  theme:
    bar:
      radius: 0
      indicator:
        radius: 0
  style_definitions:
    - id: cell_voltage_label_style
      text_color: 0xFFFFFF
      pad_left: 10
      grid_cell_x_align: STRETCH
      grid_cell_y_align: CENTER
  pages:
    - id: disconnected_page
      widgets:
        - label:
            align: CENTER
            text: "Disconnected"
        - button:
            align: CENTER
            y: 50
            widgets:
              - label:
                  align: center
                  text: "Demo Mode"
            on_click:
              then:
                - globals.set:
                    id: demo_mode
                    value: "true"
                - lvgl.page.show:
                    id: main_page
    - id: main_page
      widgets:
        - tabview:
            id: tabview_id
            position: bottom
            tabs:
              - name: Main
                id: main_tab
                widgets:
                  - <<: !include
                      file: display/.main_tab.yaml
              - name: Detail
                id: detail_tab
                widgets:
                  - <<: !include
                      file: display/.detail_tab.yaml
                      vars:
                        bms_number: 1
              - <<: !include
                  file: display/.cells_tab.yaml
                  vars:
                    bms_number: 1
              - <<: !include
                  file: display/.cells_tab.yaml
                  vars:
                    bms_number: 2

sensor:
  - platform: navitas_tac
    controller_temperature:
      name: "Controller Temperature"
    dc_bus_voltage:
      name: "DC Bus Voltage"
    battery_current:
      name: "Battery Current"
      on_value:
        then:
          - lvgl.label.update:
              id: current_label
              text:
                format: "%.1fA"
                args:
                  - "x"
    motor_rpm:
      name: "Motor RPM"
    motor_temperature:
      name: "Motor Temperature"
    speed:
      name: "Vehicle Speed"
      on_value:
        then:
          - lvgl.label.update:
              id: speed_label
              text:
                format: "%.1f"
                args:
                  - "x"
    soc:
      name: "State of Charge"
  - platform: combination
    type: sum
    name: "Total Current"
    internal: true
    sources:
      - source: bms_1_current
      - source: bms_2_current
    on_value:
      then:
        - lvgl.label.update:
            id: total_current_label
            text:
              format: "%.3fA"
              args:
                - "x"
        # - lvgl.label.update:
        #     id: current_label
        #     text:
        #       format: "%.1fA"
        #       args:
        #         - "x"

  - platform: combination
    type: max
    id: max_combined_discharge_current
    sources:
      - source: bms_1_max_discharge_current
      - source: bms_2_max_discharge_current
    on_value:
      then:
        - if:
            condition:
              lambda: !lambda |-
                static float max_current = 0.0;
                if (x > max_current) {
                  max_current = x;
                }
                return max_current;
            then:
              - lvgl.label.update:
                  id: max_combined_discharge_current_label
                  text:
                    format: "%.3fA"
                    args:
                      - "x"

text_sensor:
  - platform: navitas_tac
    navitas_tac_id: tac_controller
    gear:
      name: "Vehicle Gear"
      on_value:
        then:
          - if:
              condition:
                lambda: 'return x == "Forward";'
              then:
                - lvgl.label.update:
                    id: gear_label
                    text: "F"
                    text_color: 0x00FF00 # Green for Forward
              else:
                - if:
                    condition:
                      lambda: 'return x == "Reverse";'
                    then:
                      - lvgl.label.update:
                          id: gear_label
                          text: "R"
                          text_color: 0xFF0000 # Red for Reverse
                    else:
                      - lvgl.label.update:
                          id: gear_label
                          text: "N"
                          text_color: 0xFFFF00 # Yellow for Neutral
